# Foot — Shadcn / Zinc terminal configuration

[main]
shell=fish
login-shell=yes
term=xterm-256color
font=JetBrainsMono Nerd Font:size=16
box-drawings-uses-font-glyphs=yes
pad=24x24

[scrollback]
lines=10000
multiplier=3

[bell]
system=no
urgent=no
notify=no
visual=no

[url]
launch=xdg-open ${url}
label-letters=jfkdls;ahgurieowpq

[cursor]
style=beam
blink=yes
blink-rate=750

[colors-dark]
alpha=0.85
alpha-mode=all
blur=yes
background=0a0a0c
foreground=fafafa
cursor=0a0a0c ffffff
selection-foreground=fafafa
selection-background=27272a

regular0=18181b
regular1=ef4444
regular2=22c55e
regular3=eab308
regular4=3b82f6
regular5=a855f7
regular6=06b6d4
regular7=f4f4f5

bright0=3f3f46
bright1=f87171
bright2=4ade80
bright3=facc15
bright4=60a5fa
bright5=c084fc
bright6=22d3ee
bright7=ffffff

dim0=18181b
dim1=7f1d1d
dim2=14532d
dim3=713f12
dim4=1e3a8a
dim5=581c87
dim6=164e63
dim7=a1a1aa

[csd]
preferred=none

[key-bindings]
show-urls-launch=Control+Shift+u
unicode-input=none
