exec_always --no-startup-id dbus-update-activation-environment --systemd WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec_always --no-startup-id systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr
