# Keybindings
bindsym $mod+w exec $term
bindsym $mod+space exec sh ~/.config/wofi/launcher.sh
bindsym $mod+q kill
bindsym $mod+Shift+e exec "swaymsg exit"
bindsym $mod+Shift+r reload
bindsym $mod+y floating toggle

# Audio (PipeWire)
bindsym XF86AudioMute exec "bash -lc 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'"
bindsym XF86AudioLowerVolume exec "bash -lc 'wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-'"
bindsym XF86AudioRaiseVolume exec "bash -lc 'wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+'"

# Brightness
bindsym XF86MonBrightnessDown exec "bash -lc 'brightnessctl set 5%-'"
bindsym XF86MonBrightnessUp exec "bash -lc 'brightnessctl set 5%+'"

# Focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# Move
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Workspaces
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
